### PR TITLE
ensure console.* calls are wrapped with check on verbosity flag

### PR DESCRIPTION
**Pull request by mattberther**

### CODE REVIEW

**Comment by Apollon77** [comment]
@rogerc please accept this PR. Makes much sense for me in regard to clean logging. Thank you

**Comment by Apollon77** [comment]
@rogerc I'm very sorry to push here but the release of a fix for our users(several thousands with the affected version) is just hanging on this PR and the winston fix ... Thank you very much for your support on this. We get more and more reports of nightly crashes

**Comment by rogerc** [comment]
published new version 0.5.7. I was getting errors on node 10.15.3 so had to fix those.

**Comment by rogerc** [comment]
@mattberther  thanks for the PR

**Comment by Apollon77** [comment]
Thank you very very much!

**Pull request merged**
