### PR TITLE
Complete rewrite

### PR DESCRIPTION
**Pull request by joepie91**
After finding the code very hard to read/understand and largely broken, I've decided to do a complete rewrite from the ground up.

**I do not really expect for this PR to get merged, but wanted to provide the option anyway.** I'll be using my rewrite in my own projects, but figured it'd only be fair to at least offer the option of merging it back into this repository as well.

Changes:
- Completely rewritten.
- Added proper documentation.
- Left out a lot of apparent cruft.
- Now letting Moment.js deal with durations instead of a homebrew implementation.

Caveats:
- There are no longer any tests. I do not normally write automated tests as I find them to not really add any value, and my priority was mainly to just get the code in a functional state.
- Only `getStream` is still exposed - everything else is internal/private now.
- `date_format` is now `dateFormat`.

As some of these changes are breaking, I've incremented the major version number.

### CODE REVIEW

**Comment by hxroger** [comment]
Hi Sven,

We'll review over the next week or so. Likely is that we will take elements of it rather than taking it completely specially as you say it has breaking changes.

Roger

**Comment by MForever78** [comment]
I think you may be want to really consider this PR, because the way you use JavaScript object is wrong as far as I'm concerned.

I will switch to @joepie91 's version until you fix this.

**Comment by mikelax** [comment]
:+1: I think accepting breaking changes is fine as long as you bump the major/minor version number to indicate the changes.

**Comment by kosmasgiannis** [comment]
:+1:

**Comment by SN4T14** [comment]
:+1:

**Comment by siutsin** [comment]
:+1:

**Comment by joepie91** [comment]
Sure! If the repository and NPM package can be transferred to me, I'd be happy to take over the project.

Logistically speaking, I'd probably have to remove my fork first, before the repository could be transferred. What would you suggest as a transitioning process?

**Comment by joepie91** [comment]
That works for me.

**Comment by Shulin** [comment]
Is there an update on this? Did @joepie91 get access?

**Comment by viktort** [comment]
@danjenkins thanks for looking after this thread so diligently.

There is one project that uses this at the moment, therefore we cannot merge any potentially breaking changes. 
Can look at a tag release of what we currently have, which works, then I can discuss with team on handing over ownnership. Until then, I would advice to use a versrion that best suits your requirements.

**Comment by joepie91** [comment]
I'd release any breaking updates as a new major version, which would mean that NPM would not automatically upgrade to the new version *at all*, because of [its semantic versioning rules](https://gist.github.com/joepie91/9b9dbd8c9ac3b55a65b2#semantic-versioning).

If there's a requirement to maintain the older branch/API as well, then I don't mind agreeing on a certain maintenance period where (bugfix) updates are released for both branches. Would that solve the problem?

**Comment by hpoom** [comment]
I am happy for this repo to be handed over to t @joepie91 as long as the next release is on a new major version number. Happy for @joepie91 to take the NPM release and the repo. @shackpank or @hx-markterry can help with transferring ownership.

Sorry this took so long to resolve.

**Comment by rogerc** [comment]
The project has been worked on since this PR introducing some enhancements and cleaning some of the code up. Although far from perfect, for now its perfectly usable. At some point I will rework it again using ES6+ syntax. Thanks for your time submitting this PR.

**Pull request closed without merging**
