### PR TITLE
fix rotation when frequency is none

### PR DESCRIPTION
**Pull request by dufourgilles**
When frequency is none and just relying on file size to rotate, the max number of files is not checked.
The Rotator does not have the info about max log files and it keeps on increasing the index.
The fix propagates the limit to the rotator which does check if limit reached and reset index if needed.

Did some cleanup of all the commented code for clarity.

### CODE REVIEW

**Comment by davydof** [comment]
@rogerc friendly ping :)

**Comment by Apollon77** [comment]
I'm on vacation till 28.8. and can have a look after this too ...

**Comment by Apollon77** [comment]
@dufourgilles Ok I had  a very short look and I propose you do too ... it  seems there is a lot of unrelated stuff in there? package.json changes package names, many files removed and moved and such ... so it feels several changes came together in your branch. Please clean this up before we continue or re-estate and split into several PRs. Thank you-

**Comment by dufourgilles** [comment]
Created a new PR with minimal changes
https://github.com/rogerc/file-stream-rotator/pull/111

**Pull request closed without merging**
